// Export Utilities for X-Post Scraper
// Attached to window.ExportUtils for easy access across popup and dashboard contexts

window.ExportUtils = {
  // Helper: Trigger file download in browser
  downloadFile(content, fileName, contentType) {
    const blob = new Blob([content], { type: contentType });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = fileName;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  },

  // 1. Export as JSON
  exportToJSON(tweets, filename = "x-scraped-posts.json") {
    const jsonStr = JSON.stringify(tweets, null, 2);
    this.downloadFile(jsonStr, filename, "application/json;charset=utf-8;");
  },

  // 2. Export as CSV
  exportToCSV(tweets, filename = "x-scraped-posts.csv") {
    const headers = [
      "Tweet ID",
      "Tweet URL",
      "Display Name",
      "Handle",
      "Timestamp",
      "Text",
      "Replies",
      "Retweets",
      "Likes",
      "Views",
      "Hashtags",
      "Mentions",
      "Media URLs"
    ];

    const escapeCSV = (val) => {
      if (val === undefined || val === null) return "";
      let str = String(val);
      // Double quotes inside string must be escaped by duplicating them
      str = str.replace(/"/g, '""');
      // If cell contains commas, double quotes, or newlines, wrap in double quotes
      if (str.includes(",") || str.includes('"') || str.includes("\n") || str.includes("\r")) {
        return `"${str}"`;
      }
      return str;
    };

    let csvRows = [headers.join(",")];

    tweets.forEach(t => {
      const row = [
        escapeCSV(t.id),
        escapeCSV(t.tweetUrl),
        escapeCSV(t.userDisplayName),
        escapeCSV(t.userHandle),
        escapeCSV(t.timestamp),
        escapeCSV(t.text),
        escapeCSV(t.replies),
        escapeCSV(t.retweets),
        escapeCSV(t.likes),
        escapeCSV(t.views),
        escapeCSV(t.hashtags ? t.hashtags.join(", ") : ""),
        escapeCSV(t.mentions ? t.mentions.join(", ") : ""),
        escapeCSV(t.media ? t.media.join("; ") : "")
      ];
      csvRows.push(row.join(","));
    });

    const csvContent = "\uFEFF" + csvRows.join("\n"); // Add UTF-8 BOM for Excel compatibility
    this.downloadFile(csvContent, filename, "text/csv;charset=utf-8;");
  },

  // 3. Export as Markdown (.md)
  exportToMarkdown(tweets, filename = "x-scraped-posts.md") {
    const dateStr = new Date().toLocaleDateString();
    let md = `# Scraped X (Twitter) Posts - ${dateStr}\n\n`;
    md += `**Total Posts Scraped**: ${tweets.length}\n`;
    md += `**Generated By**: X-Post Scraper Chrome Extension\n\n`;
    md += `---\n\n`;

    tweets.forEach((t, idx) => {
      const formattedDate = new Date(t.timestamp).toLocaleString();
      md += `### ${idx + 1}. Post by ${t.userDisplayName} (${t.userHandle})\n\n`;
      md += `> ${t.text.replace(/\n/g, "\n> ")}\n\n`;
      md += `- **Engagement Metrics**:\n`;
      md += `  - 💬 **Replies**: ${t.replies.toLocaleString()}\n`;
      md += `  - 🔁 **Retweets**: ${t.retweets.toLocaleString()}\n`;
      md += `  - ❤️ **Likes**: ${t.likes.toLocaleString()}\n`;
      md += `  - 👁️ **Views**: ${t.views ? t.views.toLocaleString() : "N/A"}\n`;
      md += `- **Date/Time**: ${formattedDate}\n`;
      
      if (t.hashtags && t.hashtags.length > 0) {
        md += `- **Hashtags**: ${t.hashtags.map(h => `#${h}`).join(", ")}\n`;
      }
      
      if (t.media && t.media.length > 0) {
        md += `- **Attached Media**:\n`;
        t.media.forEach((m, mIdx) => {
          md += `  - [Media link ${mIdx + 1}](${m})\n`;
        });
      }
      
      md += `- **Original Link**: [View on X.com](${t.tweetUrl})\n\n`;
      md += `---\n\n`;
    });

    this.downloadFile(md, filename, "text/markdown;charset=utf-8;");
  },

  // 4. Export as Standalone Interactive HTML
  exportToHTML(tweets, filename = "x-scraped-posts.html") {
    const dateStr = new Date().toLocaleString();
    const dataJSON = JSON.stringify(tweets, null, 2);
    
    const htmlContent = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>X Scraper Archive</title>
  <link href="https://fonts.googleapis.com/css2?family=Outfit:wght@300;400;600;800&display=swap" rel="stylesheet">
  <style>
    :root {
      --bg: #090d16;
      --card-bg: rgba(18, 25, 41, 0.7);
      --border: rgba(255, 255, 255, 0.08);
      --border-glow: rgba(0, 242, 254, 0.25);
      --text: #f3f4f6;
      --text-muted: #9ca3af;
      --accent-blue: #4facfe;
      --accent-cyan: #00f2fe;
      --accent-gradient: linear-gradient(135deg, #00f2fe 0%, #4facfe 100%);
    }

    * {
      box-sizing: border-box;
      margin: 0;
      padding: 0;
    }

    body {
      font-family: 'Outfit', sans-serif;
      background-color: var(--bg);
      color: var(--text);
      min-height: 100vh;
      line-height: 1.5;
      padding: 2.5rem 1.5rem;
      background-image: 
        radial-gradient(at 10% 20%, rgba(0, 242, 254, 0.03) 0px, transparent 50%),
        radial-gradient(at 90% 80%, rgba(79, 172, 254, 0.03) 0px, transparent 50%);
    }

    .container {
      max-width: 1200px;
      margin: 0 auto;
    }

    header {
      text-align: center;
      margin-bottom: 3rem;
      padding: 2rem;
      background: var(--card-bg);
      border-radius: 24px;
      border: 1px solid var(--border);
      backdrop-filter: blur(12px);
      box-shadow: 0 8px 32px rgba(0, 0, 0, 0.4);
    }

    h1 {
      font-size: 2.5rem;
      font-weight: 800;
      background: var(--accent-gradient);
      -webkit-background-clip: text;
      -webkit-text-fill-color: transparent;
      margin-bottom: 0.5rem;
      letter-spacing: -1px;
    }

    .subtitle {
      color: var(--text-muted);
      font-weight: 300;
      font-size: 1rem;
    }

    .stats {
      display: flex;
      justify-content: center;
      gap: 3rem;
      margin-top: 1.5rem;
    }

    .stat-card {
      text-align: center;
    }

    .stat-val {
      font-size: 2rem;
      font-weight: 700;
      color: var(--accent-cyan);
    }

    .stat-lbl {
      font-size: 0.8rem;
      text-transform: uppercase;
      letter-spacing: 1px;
      color: var(--text-muted);
    }

    /* Controls Grid */
    .controls {
      display: flex;
      flex-wrap: wrap;
      gap: 1rem;
      margin-bottom: 2rem;
      background: var(--card-bg);
      padding: 1.25rem;
      border-radius: 16px;
      border: 1px solid var(--border);
      align-items: center;
    }

    .search-container {
      flex: 1;
      min-width: 250px;
      position: relative;
    }

    .search-input {
      width: 100%;
      background: rgba(9, 13, 22, 0.6);
      border: 1px solid var(--border);
      border-radius: 12px;
      padding: 0.75rem 1rem;
      color: #fff;
      font-size: 0.95rem;
      transition: all 0.3s ease;
    }

    .search-input:focus {
      outline: none;
      border-color: var(--accent-cyan);
      box-shadow: 0 0 10px rgba(0, 242, 254, 0.15);
    }

    .select-style {
      background: rgba(9, 13, 22, 0.6);
      border: 1px solid var(--border);
      border-radius: 12px;
      padding: 0.75rem 1.5rem;
      color: var(--text);
      font-size: 0.95rem;
      cursor: pointer;
      outline: none;
      transition: all 0.3s;
    }

    .select-style:focus {
      border-color: var(--accent-cyan);
    }

    /* Grid of Cards */
    .tweets-grid {
      display: grid;
      grid-template-columns: repeat(auto-fill, minmax(360px, 1fr));
      gap: 1.5rem;
    }

    .tweet-card {
      background: var(--card-bg);
      border-radius: 20px;
      border: 1px solid var(--border);
      padding: 1.5rem;
      display: flex;
      flex-direction: column;
      position: relative;
      transition: all 0.3s cubic-bezier(0.4, 0, 0.2, 1);
      box-shadow: 0 4px 20px rgba(0, 0, 0, 0.2);
    }

    .tweet-card:hover {
      transform: translateY(-5px);
      border-color: var(--accent-cyan);
      box-shadow: 0 8px 30px rgba(0, 242, 254, 0.1);
    }

    .tweet-author {
      display: flex;
      align-items: center;
      gap: 0.75rem;
      margin-bottom: 1rem;
    }

    .author-avatar {
      width: 48px;
      height: 48px;
      border-radius: 50%;
      border: 2px solid var(--border);
      object-fit: cover;
    }

    .author-details {
      display: flex;
      flex-direction: column;
    }

    .author-name {
      font-weight: 600;
      color: #fff;
      font-size: 1rem;
    }

    .author-handle {
      font-size: 0.85rem;
      color: var(--text-muted);
    }

    .tweet-body {
      font-size: 0.95rem;
      color: var(--text);
      white-space: pre-wrap;
      word-break: break-word;
      flex: 1;
      margin-bottom: 1.25rem;
    }

    .tweet-body a {
      color: var(--accent-cyan);
      text-decoration: none;
    }

    .tweet-body a:hover {
      text-decoration: underline;
    }

    /* Media Container */
    .media-container {
      display: grid;
      gap: 0.5rem;
      margin-bottom: 1.25rem;
      border-radius: 12px;
      overflow: hidden;
      max-height: 240px;
    }

    .media-img {
      width: 100%;
      height: 100%;
      object-fit: cover;
      max-height: 240px;
    }

    .tweet-footer {
      display: flex;
      justify-content: space-between;
      align-items: center;
      border-top: 1px solid var(--border);
      padding-top: 1rem;
      font-size: 0.8rem;
      color: var(--text-muted);
    }

    .metrics-row {
      display: flex;
      gap: 1.25rem;
    }

    .metric {
      display: flex;
      align-items: center;
      gap: 0.35rem;
    }

    .metric svg {
      width: 15px;
      height: 15px;
      fill: var(--text-muted);
    }

    .tweet-link {
      color: var(--accent-cyan);
      text-decoration: none;
      font-weight: 600;
      display: flex;
      align-items: center;
      gap: 0.25rem;
      transition: all 0.3s;
    }

    .tweet-link:hover {
      color: #fff;
    }

    .badge-date {
      display: inline-block;
      font-size: 0.75rem;
      color: var(--text-muted);
      margin-bottom: 0.5rem;
    }

    /* Empty state */
    .empty-state {
      grid-column: 1 / -1;
      text-align: center;
      padding: 4rem 2rem;
      background: var(--card-bg);
      border-radius: 20px;
      border: 1px dotted var(--border);
      color: var(--text-muted);
    }

    .empty-state svg {
      width: 48px;
      height: 48px;
      stroke: var(--text-muted);
      margin-bottom: 1rem;
    }

    ::-webkit-scrollbar {
      width: 8px;
    }
    ::-webkit-scrollbar-track {
      background: var(--bg);
    }
    ::-webkit-scrollbar-thumb {
      background: var(--card-bg);
      border-radius: 4px;
      border: 1px solid var(--border);
    }
  </style>
</head>
<body>
  <div class="container">
    <header>
      <h1>X Scraper Archives</h1>
      <p class="subtitle">Scraped Post Ledger — Extracted on ${dateStr}</p>
      
      <div class="stats">
        <div class="stat-card">
          <div class="stat-val" id="count-lbl">-</div>
          <div class="stat-lbl">Total Posts</div>
        </div>
        <div class="stat-card">
          <div class="stat-val" id="authors-lbl">-</div>
          <div class="stat-lbl">Active Authors</div>
        </div>
      </div>
    </header>

    <div class="controls">
      <div class="search-container">
        <input type="text" class="search-input" id="search-box" placeholder="Search text, authors, or hashtags...">
      </div>
      
      <select class="select-style" id="sort-selector">
        <option value="newest">Newest First</option>
        <option value="oldest">Oldest First</option>
        <option value="likes">Most Liked</option>
        <option value="retweets">Most Retweeted</option>
        <option value="views">Most Viewed</option>
      </select>
    </div>

    <div class="tweets-grid" id="grid-container">
      <!-- Tweets dynamically loaded here -->
    </div>
  </div>

  <script>
    const tweets = ${dataJSON};

    // DOM Elements
    const gridContainer = document.getElementById('grid-container');
    const searchBox = document.getElementById('search-box');
    const sortSelector = document.getElementById('sort-selector');
    const countLbl = document.getElementById('count-lbl');
    const authorsLbl = document.getElementById('authors-lbl');

    // Display Stats
    function renderStats(filteredTweets) {
      countLbl.innerText = filteredTweets.length.toLocaleString();
      const uniqueAuthors = new Set(filteredTweets.map(t => t.userHandle));
      authorsLbl.innerText = uniqueAuthors.size.toLocaleString();
    }

    // Helper formatting metrics numbers (e.g. 12500 -> 12.5K)
    function formatNumber(num) {
      if (!num) return '0';
      if (num >= 1000000) return (num / 1000000).toFixed(1).replace(/\\.0$/, '') + 'M';
      if (num >= 1000) return (num / 1000).toFixed(1).replace(/\\.0$/, '') + 'K';
      return num.toLocaleString();
    }

    // Rendering tweets
    function renderTweets() {
      const query = searchBox.value.toLowerCase().trim();
      const sort = sortSelector.value;

      // 1. Filter
      let filtered = tweets.filter(t => {
        const textMatch = t.text.toLowerCase().includes(query);
        const nameMatch = t.userDisplayName.toLowerCase().includes(query);
        const handleMatch = t.userHandle.toLowerCase().includes(query);
        const hashtagMatch = t.hashtags && t.hashtags.some(h => h.toLowerCase().includes(query));
        return textMatch || nameMatch || handleMatch || hashtagMatch;
      });

      // 2. Sort
      filtered.sort((a, b) => {
        if (sort === 'newest') return new Date(b.timestamp) - new Date(a.timestamp);
        if (sort === 'oldest') return new Date(a.timestamp) - new Date(b.timestamp);
        if (sort === 'likes') return b.likes - a.likes;
        if (sort === 'retweets') return b.retweets - a.retweets;
        if (sort === 'views') return b.views - a.views;
        return 0;
      });

      // 3. Render HTML
      gridContainer.innerHTML = '';
      renderStats(filtered);

      if (filtered.length === 0) {
        gridContainer.innerHTML = \`
          <div class="empty-state">
            <svg fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5" d="M9.172 16.172a4 4 0 015.656 0M9 10h.01M15 10h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
            </svg>
            <h3>No results found</h3>
            <p>Try refining your search terms or adjustments.</p>
          </div>
        \`;
        return;
      }

      filtered.forEach(t => {
        const localDate = new Date(t.timestamp).toLocaleString();
        
        let mediaHtml = '';
        if (t.media && t.media.length > 0) {
          mediaHtml = \`<div class="media-container">\`;
          t.media.forEach(url => {
            mediaHtml += \`<img class="media-img" src="\${url}" onerror="this.style.display='none'">\`;
          });
          mediaHtml += \`</div>\`;
        }

        // Parse hashtags
        let parsedText = t.text;
        if (t.hashtags && t.hashtags.length > 0) {
          t.hashtags.forEach(h => {
            const regex = new RegExp('#' + h, 'gi');
            parsedText = parsedText.replace(regex, \`<a href="#">#\${h}</a>\`);
          });
        }

        const card = document.createElement('div');
        card.className = 'tweet-card';
        card.innerHTML = \`
          <span class="badge-date">\${localDate}</span>
          <div class="tweet-author">
            <img class="author-avatar" src="\${t.userAvatar || 'https://abs.twimg.com/sticky/default_profile_images/default_profile_normal.png'}" onerror="this.src='https://abs.twimg.com/sticky/default_profile_images/default_profile_normal.png'">
            <div class="author-details">
              <span class="author-name">\${t.userDisplayName}</span>
              <span class="author-handle">\${t.userHandle}</span>
            </div>
          </div>
          <div class="tweet-body">\${parsedText}</div>
          \${mediaHtml}
          <div class="tweet-footer">
            <div class="metrics-row">
              <div class="metric" title="Replies">
                <svg viewBox="0 0 24 24"><path d="M14.046 2.242a9.906 9.906 0 0 0-9.93 9.927c0 2.01.592 3.879 1.614 5.457L4.4 22l4.485-1.307A9.88 9.88 0 0 0 14.046 22a9.908 9.908 0 0 0 9.93-9.927 9.906 9.906 0 0 0-9.93-9.931zm0 18.063c-1.8 0-3.487-.525-4.912-1.428l-.35-.221-2.925.852.868-2.828-.242-.375a8.03 8.03 0 0 1-1.32-4.383 8.037 8.037 0 0 1 8.056-8.056 8.04 8.04 0 0 1 8.056 8.056 8.037 8.037 0 0 1-8.056 8.056z"/></svg>
                <span>\${formatNumber(t.replies)}</span>
              </div>
              <div class="metric" title="Retweets">
                <svg viewBox="0 0 24 24"><path d="M23.77 15.67a1 1 0 0 0-1 1v2.12c0 .88-.72 1.6-1.6 1.6H3.83l2.84-2.84a1 1 0 1 0-1.42-1.42l-4.56 4.56a1 1 0 0 0 0 1.42l4.56 4.56a1 1 0 0 0 1.42 0 1 1 0 0 0 0-1.42L3.83 22.4h17.34c1.99 0 3.6-1.61 3.6-3.6v-2.12a1 1 0 0 0-1-1.01zm-19.1-7.34h17.34l-2.84 2.84a1 1 0 0 0 0 1.42 1 1 0 0 0 1.42 0l4.56-4.56a1 1 0 0 0 0-1.42L20.59 2.05a1 1 0 0 0-1.42 0 1 1 0 0 0 0 1.42l2.84 2.84H4.67c-1.99 0-3.6 1.61-3.6 3.6v2.12a1 1 0 0 0 2 0v-2.12c0-.88.72-1.6 1.6-1.6z"/></svg>
                <span>\${formatNumber(t.retweets)}</span>
              </div>
              <div class="metric" title="Likes">
                <svg viewBox="0 0 24 24"><path d="M12 21.638h-.014C9.403 21.59 1.95 14.856 1.95 8.478c0-3.064 2.525-5.754 5.403-5.754 2.29 0 3.83 1.58 4.646 2.73.814-1.148 2.353-2.73 4.644-2.73 2.88 0 5.404 2.69 5.404 5.755 0 6.377-7.452 13.11-10.035 13.157H12zM7.354 4.725c-1.782 0-3.403 1.707-3.403 3.753 0 4.887 5.795 10.748 8.042 11.148 2.248-.402 8.049-6.262 8.049-11.15 0-2.045-1.62-3.75-3.403-3.75-1.758 0-3.044 1.528-3.708 2.585a1 1 0 0 1-1.68 0c-.663-1.057-1.95-2.585-3.707-2.585z"/></svg>
                <span>\${formatNumber(t.likes)}</span>
              </div>
              <div class="metric" title="Views">
                <svg viewBox="0 0 24 24"><path d="M23.327 10.224C21.733 8.18 17.202 3 12 3S2.267 8.18.673 10.224a2.916 2.916 0 0 0 0 3.552C2.267 15.82 6.798 21 12 21s9.733-5.18 11.327-7.224a2.916 2.916 0 0 0 0-3.552zM12 19c-3.859 0-7.705-3.957-9.043-5.679a.925.925 0 0 1 0-1.1c1.338-1.722 5.184-5.679 9.043-5.679s7.705 3.957 9.043 5.679a.925.925 0 0 1 0 1.1C20.24 15.043 15.859 19 12 19zm0-11a4 4 0 1 0 0 8 4 4 0 0 0 0-8zm0 6a2 2 0 1 1 0-4 2 2 0 0 1 0 4z"/></svg>
                <span>\${formatNumber(t.views)}</span>
              </div>
            </div>
            <a class="tweet-link" href="\${t.tweetUrl}" target="_blank">
              View X
              <svg width="12" height="12" viewBox="0 0 24 24" fill="var(--accent-cyan)"><path d="M21 13v10H0V2h10v2H2v17h17v-8h2zM24 0v9h-2V3.4l-9.6 9.6-1.4-1.4L20.6 2H15V0h9z"/></svg>
            </a>
          </div>
        \`;
        gridContainer.appendChild(card);
      });
    }

    // Set up listeners
    searchBox.addEventListener('input', renderTweets);
    sortSelector.addEventListener('change', renderTweets);

    // Initial render
    renderTweets();
  </script>
</body>
</html>`;

    this.downloadFile(htmlContent, filename, "text/html;charset=utf-8;");
  }
};
